### ISSUE TITLE
Modifying AboutView Controller

### ISSUE THREAD

**Issue by SIMRAN1** [anitab-org/powerup-iOS#243]
## Description
As a developer,
I want to change the about screen so that the android and iOS version of app will be consistent..

## Mocks
![image](https://user-images.githubusercontent.com/21240014/37852182-aca7f504-2f07-11e8-9fe0-b69c23a52886.png)

## Acceptance Criteria
When About Screen is made consistent with android.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by SIMRAN1** [comment]
@sunjunkie mam please approve this issue.

**Comment by sunjunkie** [comment]
We do want consistency between Android and iOS apps. However, we also want to adhere to the standard UI practices in each ecosystem. So an iOS screen does not need to be a mirror image of the corresponding Android screen but instead should provide the same information but keep the look and feel of iOS and Apple guidelines. 
The screen shot above does not feel like an iOS App (e.g., the arrows). Also, what happens when the text is clicked?

**Comment by sunjunkie** [comment]
Also, fix the user story to conform to the format: "As a developer,
**I want to** change the about screen **so that** the android and iOS version of app will be consistent."

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I will fix the template.I really apologise for this mistake.
When the user clicks the text this happens.
![image](https://user-images.githubusercontent.com/21240014/38045589-d1c73d64-32da-11e8-8b16-a6271628898b.png)
@sunjunkie mam shall we discuss about this screen design in slack.

**Comment by sunjunkie** [comment]
You can work on the About page text display - displaying titles and then expanding the text when the title is tapped. Don't use alerts. Let's also change the titles to be consistent with each other. 

What is Powerup?
Why is Powerup needed?
How does Powerup help teenagers?

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I will send a pr for this.

**Comment by MANI14011998** [comment]
@sunjunkie ma'am i am work on this issue .i will give pr tomorrow

**Comment by sunjunkie** [comment]
@MANI14011998 OK.

**Comment by anubhavpulkit** [comment]
@sunjunkie I think AboutView looks more beautiful if the description is in one body only. And describe our idea is fewer words.

**Comment by MANI14011998** [comment]
@anubhavsingh16 I am currently working On this Issue and send the Pull request As Well
if you wants to add some more idea you can mention on pr or wait until my pr accepted

**Comment by anubhavpulkit** [comment]
@MANI14011998 I cannot send PR. I just give my suggestion I think its help you and organisation the same time.

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I work on this issue.

**Comment by sunjunkie** [comment]
You have a couple other issues to tackle first.

**Comment by anubhavpulkit** [comment]
Ok, @sunjunkie I work on this issue after completion of all pending issues. Thank You @sunjunkie

**Comment by sunjunkie** [comment]
OK. Please also see the discussion on PR #348.

**Comment by sunjunkie** [comment]
@anubhavsingh16 you can work on this.

**Comment by anubhavpulkit** [comment]
Thank you @sunjunkie
