### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by mayburgos** [anitab-org/powerup-iOS#251]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [ ] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [ ] Link all GSoC/Outreachy student's pages if applicable.
- [ ] Link Final Reports page if applicable.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by SIMRAN1** [comment]
@MeepyMay  I would like to work on it!

**Comment by anubhavpulkit** [comment]
@mayburgos Can I work on this issue?

**Comment by MANI14011998** [comment]
can I do that @sunjunkie

**Comment by sunjunkie** [comment]
@anubhavsingh16 you are welcome to work on this issue. Please let me know if you don't want to so others can.

**Comment by anubhavpulkit** [comment]
@sunjunkie I want to work on this.

**Comment by anubhavpulkit** [comment]
@mayburgos @sunjunkie I send request to edit and update the template Because the template is currently at view-only mode.

**Comment by anubhavpulkit** [comment]
@sunjunkie I think no one did Outreachy in this project.

**Comment by anubhavpulkit** [comment]
[Wiki Sidebar Update.zip](https://github.com/anitab-org/powerup-iOS/files/4271652/Wiki.Sidebar.Update.zip)

@sunjunkie Please have a look

**Comment by sunjunkie** [comment]
You need to add 2 important documentation items: 

Differences between iOS and Android Apps
Terminology for OOC event classes and utility web apps

**Comment by anubhavpulkit** [comment]
Ok @sunjunkie

**Comment by anubhavpulkit** [comment]
Done 
[Wiki Sidebar Update.zip](https://github.com/anitab-org/powerup-iOS/files/4278180/Wiki.Sidebar.Update.zip)

**Comment by sunjunkie** [comment]
Looks good. I guess you can't submit a PR for this but I approve your solution. I'll fix it when my access permissions are corrected and then close this.

**Comment by anubhavpulkit** [comment]
Thank You @sunjunkie

**Comment by anubhavpulkit** [comment]
@mayburgos @sunjunkie Can we use this updated wiki in the wiki bar.

**Comment by sunjunkie** [comment]
I moved your changes into the wiki sidebar. Thank you @anubhavsingh16.
