### ISSUE TITLE
View Controllers with minor differences should be merged into one

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/powerup-iOS#282]
## Description
As a developer,
I want to reduce duplication of view controllers,
so that I can reduce errors resulting from view controllers getting out of sync.

## Mocks
See Results View Controller and Completed View Controller in the storyboard. 

### Update [Required]
- [ ] View Controllers that have only minor differences from each other should be merged.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by swatisingh45** [comment]
Hey! can I work on this issue?

**Comment by sunjunkie** [comment]
Sure, go ahead. Let me know if you have any questions.

**Comment by anubhavpulkit** [comment]
@sunjunkie Can you give a little brief on this issue.

**Comment by sunjunkie** [comment]
The 2 view controllers (Results View Controller and Completed View Controller) look identical. We should not have 2 identical view controllers. We should just have one in the storyboard and merge the underlying code.

**Comment by anubhavpulkit** [comment]
Ok, I will try to solve this issue.

**Comment by anubhavpulkit** [comment]
@sunjunkie I will send PR on this issue today I'm working on this issue.

**Comment by anubhavpulkit** [comment]
@sunjunkie **NEED HELP** I stuck in the backend of CompletedViewController and ResultViewController How I can move the code of completedViewController to ResultViewController because it works fine without changing anything in code.

**Comment by sunjunkie** [comment]
@anubhavsingh16 Remove the unused view controllers and their code files and the run the app. If you haven't merged any code I would expect lots if issues.

**Comment by anubhavpulkit** [comment]
Ok @sunjunkie, I will try to do as early as possible.

**Comment by anubhavpulkit** [comment]
@sunjunkie I solve this issue any update in my recent commit. I remove unused view controller as well as their code files and it run fine.
